-- Schema for Bank & Employee Management Database 

-- 1. Customers Table
CREATE TABLE Customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    age NUMBER CHECK (age >= 0),
    is_vip VARCHAR2(5) DEFAULT 'FALSE' CHECK (is_vip IN ('TRUE', 'FALSE'))
);

-- 2. Accounts Table
CREATE TABLE Accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER REFERENCES Customers(customer_id) ON DELETE CASCADE,
    account_type VARCHAR2(20) CHECK (account_type IN ('Savings', 'Checking')),
    balance NUMBER(15, 2) DEFAULT 0.00 CHECK (balance >= 0)
);

-- 3. Loans Table
CREATE TABLE Loans (
    loan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER REFERENCES Customers(customer_id) ON DELETE CASCADE,
    principal_amount NUMBER(15, 2) NOT NULL,
    interest_rate NUMBER(5, 2) NOT NULL, -- e.g., 5.50 for 5.5%
    due_date DATE NOT NULL
);

-- 4. Employees Table
CREATE TABLE Employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    department VARCHAR2(50) NOT NULL,
    salary NUMBER(15, 2) NOT NULL CHECK (salary >= 0)
);
